
# CONFIGURACION DE BASE DE DATOS
spring.datasource.url=jdbc:mysql://localhost:3306/cine_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# CONFIGURACION JPA/HIBERNATE
# update = usa las tablas existentes sin borrarlas
spring.jpa.hibernate.ddl-auto=update
# Muestra las consultas SQL en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# CONFIGURACION DEL SERVIDOR
server.port=8080

# CONFIGURACION THYMELEAF
# Desactiva el cache para ver cambios sin reiniciar
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
